### ISSUE TITLE
老哥，elasticsearch类型转换异常你怎么解决的？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [Leme34/leyouCity#2]
java.lang.ClassCastException: class org.elasticsearch.search.aggregations.bucket.terms.ParsedLongTerms cannot be cast to class org.elasticsearch.search.aggregations.bucket.terms.LongTerms (org.elasticsearch.search.aggregations.bucket.terms.ParsedLongTerms and org.elasticsearch.search.aggregations.bucket.terms.LongTerms are in unnamed module of loader 'app')

**Comment by Leme34** [comment]
> java.lang.ClassCastException: class org.elasticsearch.search.aggregations.bucket.terms.ParsedLongTerms cannot be cast to class org.elasticsearch.search.aggregations.bucket.terms.LongTerms (org.elasticsearch.search.aggregations.bucket.terms.ParsedLongTerms and org.elasticsearch.search.aggregations.bucket.terms.LongTerms are in unnamed module of loader 'app')

请给出报错代码具体上下文 谢谢

**Comment by SaltedFish-Extreme** [comment]
> > java.lang.ClassCastException：org.elasticsearch.search.aggregations.bucket.terms.ParsedLongTerms类不能转换为org.elasticsearch.search.aggregations.bucket.terms.LongTerms类（org.elasticsearch.search.search.aggregation.bucket.terms .ParsedLongTerms和org.elasticsearch.search.aggregations.bucket.terms.LongTerms位于加载程序“ app”的未命名模块中）
> 
> 请指定报错代码具体细节谢谢

老哥，我解决问题了，把StringTerms和LongTerms换成父类Terms就好了
